# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Digest-Hashcash
version:      0.03
version_from: Hashcash.pm
installdirs:  site
requires:
    Time::HiRes:                   1.2
    Time::Local:                   0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.23
