#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Digest-Hashcash
version:      0.02
version_from: Hashcash.pm
installdirs:  site
requires:
    Time::Local:                   0
    Time::HiRes:                   1.2

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.10_07
