#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Digest-Hashcash
version:      0.01
version_from: Hashcash.pm
installdirs:  site
requires:

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.10_07
